stages:
  - create-dockerfile
  - build-image

workflow:
  rules:
    - if: $CI_COMMIT_TAG

default:
  # Always allow the pipeline to finish despite new ones have been triggered
  interruptible: false

.supported_os_list: &supported_os_list
  - 'debian10'
  - 'debian11'
  - 'debian12'
  - 'el7'
  - 'el8'
  - 'el9'
  - 'ubuntu2004'
  - 'ubuntu2204'
  - 'ubuntu2404'

create-dockerfile:
  stage: create-dockerfile
  image: alpine:latest
  parallel:
    matrix:
      - SUPPORTED_OS: *supported_os_list
  script:
    # bash and wget are dependencies for create_docker_files.sh
    - apk add --no-cache bash wget
    - ./create_docker_files.sh ${SUPPORTED_OS}
  artifacts:
    paths:
      - DockerDir_${SUPPORTED_OS}
    expire_in: 1 days

build-image:
  stage: build-image
  image:
    # See the GitLab documentation: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  parallel:
    matrix:
      - SUPPORTED_OS: *supported_os_list
  script:
    - echo "{\"auths\":{\"${DOCKERHUB_REGISTRY}\":{\"auth\":\"${DOCKERHUB_AUTH}\"}}}" > /kaniko/.docker/config.json
    # We push to the container registry and Docker Hub
    # In addition, we push the "untagged" images to automatically create the "latest" tag
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/DockerDir_${SUPPORTED_OS}"
      --dockerfile "${CI_PROJECT_DIR}/DockerDir_${SUPPORTED_OS}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/belle2-base-${SUPPORTED_OS}:${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}/belle2-base-${SUPPORTED_OS}"
      --destination "${DOCKERHUB_ORGANIZATION}/belle2-base-${SUPPORTED_OS}:${CI_COMMIT_TAG}"
      --destination "${DOCKERHUB_ORGANIZATION}/belle2-base-${SUPPORTED_OS}"
  dependencies:
    - create-dockerfile